# Generated by axhub import
FROM python:3.12-slim

WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PORT=8502
COPY . .
RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
RUN if [ -f pyproject.toml ]; then pip install --no-cache-dir .; fi
EXPOSE 8502
CMD ["sh", "-c", "python oot_alarm.py & exec python -m uvicorn dashboard_api:app --host 0.0.0.0 --port ${PORT:-8502}"]
